export { AboutUs } from "./AboutUs.jsx";
export { Home } from "./Home.jsx";
export { Login } from "./Login.jsx";
export { AddCompany } from "./AddCompany.jsx";
export { AddEntry } from "./AddEntry.jsx";
export { Companies } from "./Companies.jsx";
export { ContactUs } from "./ContactUs.jsx";
export { StudentDetail } from "./StudentDetail.jsx";
export { Students } from "./Students.jsx";
